### ISSUE TITLE
Send and Sync not implemented for Ftdi

### ISSUE THREAD

**Issue by Icxolu** [ftdi-rs/libftd2xx#56]
Is there a specific reason that `Ftdi` can not implement the `Send` and `Sync` traits?

Right now the auto traits are not implemented because the struct contains a (type aliased) raw pointer (`FT_HANDLE`), which are not `Send` and `Sync`.

Is this intentional because `ftd2xx` does not support it or just an oversight of the auto trait impls?

**Comment by newAM** [comment]
Not intentional, just an oversight.

I don't see any reason it can't be `Send` and `Sync`.  Do you want to change this or should I?

**Comment by Icxolu** [comment]
Thanks for the clarification.

I can send a PR fixing this later.
